name: React build
on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: lol-duo-images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build and tag Docker image
        env:
          ECR_REGISTRY: public.ecr.aws/x6k4k7p6
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
      - name: Push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/x6k4k7p6
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x6k4k7p6
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA